leftnav:
- identifier: 5d291b6d-948f-427f-a9e7-8acc9b61fbe6
  name: '21'
  pageRef: /external-resources/21
  weight: 10
- identifier: d50b61ca-14e1-418d-a4b0-99d6a1a583c8
  name: '20'
  pageRef: /external-resources/20
  weight: 20
- identifier: 259f35ff-47cc-424b-8209-8af5b035970e
  name: '19'
  pageRef: /external-resources/19
  weight: 30
- identifier: bc6c31da-9183-4e49-a133-b0255079c4f9
  name: '18'
  pageRef: /external-resources/18
  weight: 40
- identifier: 1ebd6590-00e4-420b-88f0-b6d5ea7bc433
  name: '17'
  pageRef: /external-resources/17
  weight: 50
- identifier: a40a38f4-608c-4e6d-9377-e89bfffe1109
  name: '16'
  pageRef: /external-resources/16
  weight: 60
- identifier: 886d2881-51a4-440c-a060-96d0336a22ee
  name: '15'
  pageRef: /external-resources/15
  weight: 70
- identifier: 1c6966c2-ba56-4ee6-af58-e6451c35a0e5
  name: '14'
  pageRef: /external-resources/14
  weight: 80
- identifier: 02c42c4d-b1e6-421f-9c77-bff68d8ab725
  name: '13'
  pageRef: /external-resources/13
  weight: 90
